import Head from "next/head";
import Form from "../src/components/Form";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pay Me</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Form />
      </main>
    </div>
  );
}
